# Generated by Django 6.0.6 on 2026-06-21 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_number', models.IntegerField()),
                ('label', models.CharField(max_length=30)),
                ('prompt_template', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key_number'],
                'unique_together': {('user', 'key_number')},
            },
        ),
    ]
