# Generated by Django 6.0.6 on 2026-06-21 10:42

import django.db.models.deletion
import sharing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('share_code', models.CharField(default=sharing.models.generate_share_code, max_length=6, unique=True)),
                ('share_type', models.CharField(choices=[('persona', 'Persona'), ('prompt', 'Prompt')], default='prompt', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_prompts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
